$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$audioDir = Join-Path $root 'assets\audio'
$output = Join-Path $root 'src\EmbeddedAudio.g.cs'

function Get-ByteArrayLiteral {
    param([byte[]]$Bytes)
    $chunks = New-Object System.Collections.Generic.List[string]
    for ($i = 0; $i -lt $Bytes.Length; $i += 16) {
        $slice = $Bytes[$i..([Math]::Min($i + 15, $Bytes.Length - 1))]
        $chunks.Add(($slice | ForEach-Object { $_.ToString() }) -join ', ')
    }
    return ($chunks -join ",`r`n            ")
}

$startPath = Join-Path $audioDir 'recording-start.wav'
$completePath = Join-Path $audioDir 'recording-complete.wav'
if (-not (Test-Path -LiteralPath $startPath)) {
    & (Join-Path $PSScriptRoot 'Generate-RecordingCue.ps1')
}
if (-not (Test-Path -LiteralPath $startPath) -or -not (Test-Path -LiteralPath $completePath)) {
    throw 'Missing recording cue WAV files.'
}

$startBytes = [IO.File]::ReadAllBytes($startPath)
$completeBytes = [IO.File]::ReadAllBytes($completePath)

$content = @"
// <auto-generated by tools/Embed-Audio.ps1 — do not edit>
namespace Flowtype
{
    internal static class EmbeddedAudio
    {
        internal static readonly byte[] RecordingStart = new byte[]
        {
            $(Get-ByteArrayLiteral $startBytes)
        };

        internal static readonly byte[] RecordingComplete = new byte[]
        {
            $(Get-ByteArrayLiteral $completeBytes)
        };
    }
}
"@

[IO.File]::WriteAllText($output, $content, [Text.UTF8Encoding]::new($false))
Write-Host "Wrote $output ($($startBytes.Length) + $($completeBytes.Length) bytes)"
